### ISSUE TITLE
Thoughts & comments

### ISSUE THREAD

**Issue by eioo** [rareagency/rareagency.fi#41]

**Comment by eioo** [comment]
Very nice website!

**Comment by eioo** [comment]
Test

**Comment by naftis** [comment]
eka

**Comment by rikukissa** [comment]
oisko daim-reseptiä heittää

**Comment by Keksike** [comment]
voitko kommaa takas?? mulla vaa tunti netti aikaa päiväs daiju mutsi ei anna pelaa runee rauhas

**Comment by ollija** [comment]
Mikkä teidän KD:t on? Itel melkein yli 2 lol

**Comment by psycotimi** [comment]
Mitä noobeja, ette oo osannu ees laittaa liekkianimaatiota tein sivuille.

**Comment by Cadiac** [comment]
<script>alert("owned")</script>

**Comment by kaupunki-apina** [comment]
I can give my Bayonet Doppler for all of your csgo graffities and cases, link in my bio

**Comment by tuomasj** [comment]
Be like Tuomas

**Comment by tuomasj** [comment]
Use headset with a microphone

**Comment by hetenho** [comment]
Hi! I just tried to reach you on LinkedIn! Your profile looks very promising and I would like to take the time and talk to you for a bit.

**Comment by ilmariMantysaari** [comment]
Vaihdetaan 2 pläsää hyvään runeukkoon.

**Comment by mikko** [comment]
'; drop table users; --

**Comment by mikko** [comment]
https://www.si.edu/sites/default/files/newsdesk/photos/jn2018-00036.jpg

**Comment by mieky** [comment]
tampereen top5 porkkalat ???

**Comment by mikko** [comment]
![nalle](https://www.si.edu/sites/default/files/newsdesk/photos/jn2018-00036.jpg)

**Comment by jkumara** [comment]
seuraa 08-alueelta??

**Comment by alppucodes** [comment]
😘 HOT 🔥 SINGLE 👌 MONS 👄 LOOKING 👀 FOR 👨‍🦰 IN ❤️YOU’RE 😈AREA 💯

**Comment by Mutjake** [comment]
logo lehmä

**Comment by anttiviljami** [comment]
Hei! Koitin lähettää tarjouspyynnön, mutta faksi ei toimi. Oletteko yhteyksissä +358504305025

**Comment by eetu** [comment]
Ihan on tekijöidensä näköinen!

**Comment by tomilaine** [comment]
Betasta huolimatta ei oo työmaan merkkiä, eli rare tekee heti valmista! 💪💋

**Comment by apkoponen** [comment]
My cursor is so lit! 🔥

**Comment by eioo** [comment]
Web-kehityksen spektaakkeli, ei voi muuta sanoa kun hattua nostaa!

**Comment by vuorinvi** [comment]
<img src="https://i7.pngguru.com/preview/735/995/751/know-your-meme-t-shirt-image-drawing-meme.jpg"/>

**Comment by Kitsupitsu** [comment]
Juontaja paljonko viive

**Comment by vjandrei** [comment]
Daimin ohje kiitos

**Comment by eioo** [comment]
**Ohje:**

 - 2 dl vaaleaa siirappia
 - 2 dl kermaa
 - 2 dl sokeria
 - 2 rkl mantelirouhetta tai jauhetta (itse käytin mantelijauheen
   sihtaamisessa jääneet suuremmat palat tähän)
 - 2 rkl voita
 - 150 g maitosuklaata (marabou)


 1. **Mittaa** siirappi, kerma, mantelirouhe ja sokeri kattilaan. Kiehauta
    ja keitä miedolla lämmöllä 130-140 asteiseksi (mitä korkeampi aste
    sitä kovempaa ja rapeampaa daimia saat). Lisää voi sulattamalla se
    seokseen. Sekoita seosta koko ajan (varsinkin loppupuolella) ja varo
    polttamasta. Seos paksuuntuu keittämisen aikana, johon menee noin 20
    minuuttia.
 2. **Levitä/kaada** kinuski ohuelti leivinpaperilla vuoratulle
    pellille/vuoalle lastaa apuna käyttäen. Halutessasi vedä ohuet
    viillot kinuskiin ennen kuin se jähmettyy, jotta sinulla on valmiita
    paloja, kun kinuski on kovaa. Seos jämähtää melko nopesti, joten ole
    tarkka. Viillot eivät ole välttämättömyys, voit taitella palat myös
    jähmettymisen jälkeen mielesi mukaan.
 3. **Sulata** maitosuklaa vesihauteessa ja voitele kinuskipalat sulalla
    suklaalla pensseliä/sutia apuna käyttäen.
 4. Laita suklaalla voidellut Daimit nyt jääkaappiin jähmettymään.

**Lähde**: [anniuunissa.fi](https://www.anninuunissa.fi/diy-helppo-kotitekoinen-dai/)

**Comment by naftis** [comment]
klkk

**Comment by ekantola** [comment]
a';DROP TABLE users; SELECT * FROM userinfo WHERE 't' = 't
